# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Clone and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clone
      run: git clone -b gh-pages https://github.com/Drelf2018/nana7mi.link.git
    - name: Remove
      run: rm -rf ./nana7mi.link/.git
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: release # The branch the action should deploy to.
        folder: .