name: build-go-binary

on:
  release:
    types: [published] # 表示在发布新的 Release 时触发

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows] # 需要打包的系统
        goarch: [amd64] # 需要打包的架构
    steps:
      - uses: actions/checkout@v3
      - name: Generate
        run: |
          go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest
          export PATH=$PATH:/home/runner/go/bin
          go generate
        working-directory: cmd/webhook
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 一个默认的变量，用来实现往 Release 中添加文件
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.18
          project_path: cmd/webhook # 修改 go build 目录
          md5sum: false # 同时生成 md5 文件 这就没必要了
          compress_assets: OFF # 自动打包 不要！
