name: build-go-binary

on:
  release:
    types: [published] # 表示在发布新的 Release 时触发

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows] # 需要打包的系统
        goarch: [amd64, arm64] # 需要打包的架构
    steps:
      - name: Export version
        run: export webhook=${{ github.ref_name }}
      - name: Install
        run: go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 一个默认的变量，用来实现往 Release 中添加文件
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: https://go.dev/dl/go1.21.0.linux-amd64.tar.gz # 可以指定编译使用的 Golang 版本
          pre_command: go test
          project_path: cmd/build # 修改 go build 目录
          md5sum: false # 同时生成 md5 文件 这就没必要了
          compress_assets: OFF # 自动打包 不要！
